name: chat_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  flutter_bloc: ^8.1.1
  go_router: ^6.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
