name: chat_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  file_picker: null
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  go_router: ^6.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter_icons:
  image_path: "assets/splash_img.png"
  android: true
  ios: true
  
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
